version: '3'
services:
  psql:
    image: hjm0520/postgres:v1
    container_name: psql
    environment:
      - POSTGRES_DB=devops
      - POSTGRES_USER=devops
      - POSTGRES_PASSWORD=devops

  devops:
    image: hjm0520/devops:v1
    build: .
    command: /bin/sh -c "create_super_user.sh"
    volumes:
      - .:/opt/devops
    ports:
      - "8000:8000"
    depends_on:
      - psql
    container_name: devops
